services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=database
      - DB_NAME=vacation
      - DB_USER=root
      - DB_PASS=root
    depends_on:
      - database
    networks:
      - vacation_net
  database:
    image: mariadb:10.5
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vacation
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - vacation_net
networks:
  vacation_net:
    driver: bridge

volumes:
  db_data: